### ISSUE TITLE
checklist for bioC submission

### ISSUE THREAD

**Issue by patrickjdanaher** [Nanostring-Biostats/InSituType#170]
- [x] Add MIT license
- [ ] look at dependency licenses down to the 2nd order (see note below for a list of 2nd order dependencies)
- [x] confirm there's a test for every exported function
- [x] issue 161 - subclustering correction
- [x] Check roxygen documentation - plenty of incomplete / outdated docs right now
- [x] clean up the code detritus in rescaleProfiles.R
- [x] speed up geosketch
